apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
        containers:
        - name: consignment-service
          image: ewanvalentine/consignment:latest
          imagePullPolicy: Always
          command: [
            "./shippy-consignment-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          env:
          - name: DB_HOST
            value: "mongo:27017"
          - name: UPDATED_AT
            value: "Tue 20 Mar 2018 13:58:08 GMT"
          ports:
          - containerPort: 8080
            name: cons-port
